INSERT INTO GBS.USER(USER_NAME, PASSWORD, EMAIL, ORGNIZATION_ID, CREATED_BY, CREATED_ON, UPDATED_BY, UPDATED_ON , ENABLE) 
VALUES('Lulwa.almuhana@fdpm.gov.bh', '$2a$10$IoCRoUasxP8KjsnPwh9MJehkQurtIFRiqMDvAoBnwRw0pDa5AOSra', 'lulwa.almuhana@fdpm.gov.bh', NULL, NULL, '2017-02-22 14:11:52', NULL, NULL , 1);

INSERT INTO GBS.USER(USER_NAME, PASSWORD, EMAIL, ORGNIZATION_ID, CREATED_BY, CREATED_ON, UPDATED_BY, UPDATED_ON , ENABLE) 
VALUES('fahad.alkhalifa@fdpm.gov.bh', '$2a$10$Ba9KPsOmXpzPQJdWN1a1Zu3rs6uEjCNYL7KbTGY8fWFoONixHDB1G', 'fahad.alkhalifa@fdpm.gov.bh', NULL, NULL, '2017-02-22 14:11:52', NULL, NULL , 1);

INSERT INTO GBS.USER(USER_NAME, PASSWORD, EMAIL, ORGNIZATION_ID, CREATED_BY, CREATED_ON, UPDATED_BY, UPDATED_ON , ENABLE) 
VALUES('Islam.Ghunaim@fdpm.gov.bh', '$2a$10$qU4UofVyAyqjE8QKwLWWMOUs0iEhi4G9ftLMn4eA3Y/kaA9jXbeBi', 'islam.ghunaim@fdpm.gov.bh', NULL, NULL, '2017-02-22 14:11:52', NULL, NULL , 1);

INSERT INTO GBS.USER(USER_NAME, PASSWORD, EMAIL, ORGNIZATION_ID, CREATED_BY, CREATED_ON, UPDATED_BY, UPDATED_ON , ENABLE) 
VALUES('yousif.khalaf@fdpm.gov.bh', '$2a$10$DrlV..kPG9xLjQOx/qEIgeIbXQqL1Yl6NAY5teVHcnzOku8HGqrcm', 'yousif.khalaf@fdpm.gov.bh', NULL, NULL, '2017-02-22 14:11:52', NULL, NULL , 1);

INSERT INTO GBS.USER(USER_NAME, PASSWORD, EMAIL, ORGNIZATION_ID, CREATED_BY, CREATED_ON, UPDATED_BY, UPDATED_ON , ENABLE) 
VALUES('Nasser.Alnoaimi@fdpm.gov.bh', '$2a$10$UiSQuuKu7MHh1NeBqplGd.kPom6r7UGYEMsrWmEqwsHQZ/1j4qGDi', 'nasser.alnoaimi@fdpm.gov.bh', NULL, NULL, '2017-02-22 14:11:52', NULL, NULL , 1);

INSERT INTO GBS.USER(USER_NAME, PASSWORD, EMAIL, ORGNIZATION_ID, CREATED_BY, CREATED_ON, UPDATED_BY, UPDATED_ON , ENABLE) 
VALUES('fadheela.almutawa@fdpm.gov.bh', '$2a$10$AzASjjm.FEepkyTsHnAm4OES6cW/nUEWqPzfNGTy570vPAB3ohZde', 'fadheela.almutawa@fdpm.gov.bh', NULL, NULL, '2017-02-22 14:11:52', NULL, NULL , 1);


INSERT INTO GBS.USER_GROUP(USER_ID, GROUP_ID) 
	VALUES((SELECT USER_ID FROM GBS.USER WHERE LOWER(USER_NAME) = LOWER('Lulwa.almuhana@fdpm.gov.bh')), (SELECT GROUP_ID FROM GBS.GROUP WHERE LOWER (GROUP_NAME) = LOWER('USER_GROUP')));

INSERT INTO GBS.USER_GROUP(USER_ID, GROUP_ID) 
	VALUES((SELECT USER_ID FROM GBS.USER WHERE LOWER(USER_NAME) = LOWER('Lulwa.almuhana@fdpm.gov.bh')), (SELECT GROUP_ID FROM GBS.GROUP WHERE LOWER (GROUP_NAME) = LOWER('ADMIN_GROUP')));

	
	
INSERT INTO GBS.USER_GROUP(USER_ID, GROUP_ID) 
	VALUES((SELECT USER_ID FROM GBS.USER WHERE LOWER(USER_NAME) = LOWER('fahad.alkhalifa@fdpm.gov.bh')), (SELECT GROUP_ID FROM GBS.GROUP WHERE LOWER (GROUP_NAME) = LOWER('USER_GROUP')));

INSERT INTO GBS.USER_GROUP(USER_ID, GROUP_ID) 
	VALUES((SELECT USER_ID FROM GBS.USER WHERE LOWER(USER_NAME) = LOWER('fahad.alkhalifa@fdpm.gov.bh')), (SELECT GROUP_ID FROM GBS.GROUP WHERE LOWER (GROUP_NAME) = LOWER('ADMIN_GROUP')));

	
INSERT INTO GBS.USER_GROUP(USER_ID, GROUP_ID) 
	VALUES((SELECT USER_ID FROM GBS.USER WHERE LOWER(USER_NAME) = LOWER('Islam.Ghunaim@fdpm.gov.bh')), (SELECT GROUP_ID FROM GBS.GROUP WHERE LOWER (GROUP_NAME) = LOWER('USER_GROUP')));

INSERT INTO GBS.USER_GROUP(USER_ID, GROUP_ID) 
	VALUES((SELECT USER_ID FROM GBS.USER WHERE LOWER(USER_NAME) = LOWER('Islam.Ghunaim@fdpm.gov.bh')), (SELECT GROUP_ID FROM GBS.GROUP WHERE LOWER (GROUP_NAME) = LOWER('ADMIN_GROUP')));
	
	
INSERT INTO GBS.USER_GROUP(USER_ID, GROUP_ID) 
	VALUES((SELECT USER_ID FROM GBS.USER WHERE LOWER(USER_NAME) = LOWER('yousif.khalaf@fdpm.gov.bh')), (SELECT GROUP_ID FROM GBS.GROUP WHERE LOWER (GROUP_NAME) = LOWER('USER_GROUP')));

INSERT INTO GBS.USER_GROUP(USER_ID, GROUP_ID) 
	VALUES((SELECT USER_ID FROM GBS.USER WHERE LOWER(USER_NAME) = LOWER('yousif.khalaf@fdpm.gov.bh')), (SELECT GROUP_ID FROM GBS.GROUP WHERE LOWER (GROUP_NAME) = LOWER('ADMIN_GROUP')));
	
	
INSERT INTO GBS.USER_GROUP(USER_ID, GROUP_ID) 
	VALUES((SELECT USER_ID FROM GBS.USER WHERE LOWER(USER_NAME) = LOWER('Nasser.Alnoaimi@fdpm.gov.bh')), (SELECT GROUP_ID FROM GBS.GROUP WHERE LOWER (GROUP_NAME) = LOWER('USER_GROUP')));

INSERT INTO GBS.USER_GROUP(USER_ID, GROUP_ID) 
	VALUES((SELECT USER_ID FROM GBS.USER WHERE LOWER(USER_NAME) = LOWER('Nasser.Alnoaimi@fdpm.gov.bh')), (SELECT GROUP_ID FROM GBS.GROUP WHERE LOWER (GROUP_NAME) = LOWER('ADMIN_GROUP')));
	
	
INSERT INTO GBS.USER_GROUP(USER_ID, GROUP_ID) 
	VALUES((SELECT USER_ID FROM GBS.USER WHERE LOWER(USER_NAME) = LOWER('fadheela.almutawa@fdpm.gov.bh')), (SELECT GROUP_ID FROM GBS.GROUP WHERE LOWER (GROUP_NAME) = LOWER('USER_GROUP')));

INSERT INTO GBS.USER_GROUP(USER_ID, GROUP_ID) 
	VALUES((SELECT USER_ID FROM GBS.USER WHERE LOWER(USER_NAME) = LOWER('fadheela.almutawa@fdpm.gov.bh')), (SELECT GROUP_ID FROM GBS.GROUP WHERE LOWER (GROUP_NAME) = LOWER('ADMIN_GROUP')));




