smartApp.constant('BASE_CONSTS', (function() {
	  // Define your constant
	  return {
	    SHORT: 'short',
	    LONG: 'long',
	    SELECT_FILE_FIRST_MSG : 'من فضلك اختر الملف اولا',
	    UPLOAD_SUCCESSFULLY_MSG : 'تم تحميل الملف بنجاح',
	    NUMBER : ' رقم ',
	    YEAR : ' لسنة ',
	    CREATE_BOARD_TITLE : 'إنشاء لجنة / مجلس',
	    BOARD_NAME_LABEL:'اسم اللجنة / مجلس الادارة',
	    BOARD_SOURCE_OARGNIZATION_LABEL : 'الجهة المعنية بالتعيين',
	    HEGRAY_LABLE : 'هجرى',
	    MELADY_LABEL :'ميلادى',
	    ISSUE_DATE_DECREE_LABEL : 'تاريخ إصدار الأداة التشريعية',
	    END_DATE_DECREE_LABLE : 'تاريخ الانتهاء',
	    START_DATE_DECREE_LABLE : 'تاريخ الإنشاء',
	    BOARD_DESTINATION_ORGANIZATION_LABEL : 'الجهة المعنية',
	    CPR_NUMBER_LABLE : 'الرقم الشخصي',
	    MEMBER_NAME_LABLE : 'اسم العضو',
	    MEMBER_OCCUPATION_LABLE :'المسمى الوظيفي',
	    MEMEBR_ONBEHALF_OF_LABLE : 'ممثل عن',
	    MEMBER_ROLE_LABEL : 'الصفة',
	    MEMBER_ORGANIZATION_LABEL :'الجهة',
	    MEMBER_END_DATE_LABEL:'تاريخ انتهاء العضوية',
	    MEMBER_START_DATE_LABEL : 'تاريخ الانضمام',
	    ADD_BUTTON_LABEL:'إضافة',
	    UPDATE_BUTTON_LABEL:'تعديل',
	    DECREE_TYPE_LABEL:'نوع الأداة  التشريعية',
	    DECREE_NUMBER_LABEL:'رقم الأداة  التشريعية',
	    DECREE_YEAR_LABEL:'سنة الأداة  التشريعية',
	    CHOOSE_FILE_LABEL :'اختر الملف',
	    SAVE_FILE_LABEL:'إدراج',
	    ATTACHMENT_NAME_LABEL:'المرفق',
	    ATTACHMENT_CREATION_DATE_LABEL:'تاريخ الإرفاق',
	    UPDATE_DELETE_LABEL : 'تعديل/حذف',
	    DECREE_LABLE : 'الأداة  التشريعية',
	    CPR_NUMBER_LENGTH:'9',
	    BOARD_LABEL : 'لجنة',
	    COMMITTE_LABEL : 'مجلس',
	    SEARCH_COMMITTE_LABEL_ : 'مجلس إدارة',
	    DECREE_YEAR_ERROR_MSG : 'سنة الأداة  التشريعية يجب ان تتكون من 4 أرقام  وأن  تكون نفس السنة الحالية أو  سنوات سابقة وليست لاحقة',
	    ATTACHMENT_TYPE_LABEL : 'نوع المرفق',
	    DECREE_ALREADY_EXISTS : 'هذا المرجع موجود من قبل',
	    ATTACHMENT_DECREE : 'مرجع',
	    NOTIFICATIONS_TITLE : 'التنبيهات',
	    MEMBERS_TITLE : 'الأعضاء',
	    DECREES_TITLE : 'المراجع',
	    SAVE_BOARD : '(حفظ  (اللجنة /المجلس',
	    NOTIFICATION_BEFORE_LABEL : 'التنبية قبل',
	    NOTIFICATION_REPEAT_LABEL : 'التنبية كل',
	    INAVLID_CPR_NUMBER : 'الرقم الشخصي غير صحيح ، الرجاء إعادة إدخاله ',
	    CPR_NUMBER_9_DIGITS : 'الرقم الشخصى يتكون من 9 أرقام  فقط',
	    ERROR_ADDING_MORE_THAN_MEMBER_WITH_SAME_CPRNUMBER : 'لايمكن إضافة  صاحب الرقم الشخصى {cprNumber} اكثر من مرة لنفس (اللجنة /المجلس) . رجاءً  إعادة الإدخال ',
	    ERROR_ADDING_MORE_THAN_MEMBER_WITH_SAME_NAME : 'لا يُسمح بإضافة العضو  {NAME} أكثر  من مرة لنفس (اللجنة/المجلس). رجاءً  إعادة الادخال ',
	    ERROR_ADDING_NAME_WITHOUT_CPRNUMBER : 'يُسمح بإضافة العضو باستخدام الرقم الشخصي  أو  الاسم فقط',
	    ERROR_ADDING_MEMBER_WITH_TITLE_AND_NO_ORGANIZATION_OR_VICEVERSA : 'لا يُسمح بإضافة  العضو التابع لجهة بدون مسمى وظيفي  أو  العكس',
	    BOOLEAN_FALSE	:'false',
	    BOOLEAN_TRUE	:'true',
	    MEMBER_START_DATE_BEFORE_END_DATE : 'لا يُسمح  بأن  يكون تاريخ انتهاء العضوية اقل من تاريخ الانضمام',
	    MEMBER_START_DATE_AND_END_DATE_REQUIRED : 'يجب إدخال تاريخ الانضمام وتاريخ انتهاء العضوية ',
	    MEMBER_ROLE_EXISTS_BEFORE : 'لا يُسمح بإضافة أكثر من رئيس أو أمين سر أو مدقق مالي  في نفس المجلس/ اللجنة، الرجاء تعديل الصفة',
	    DECREE_YEAR_IS_INVALID : 'سنة الأداة  التشريعية لا يُسمح  بأن تكون أكبر من السنة الحالية ',
	    DECREE_YEAR_REQUIRED : 'يجب إدخال سنة الأداة  التشريعية',
	    DECREE_NUMBER_ERROR_MSG : 'رقم الأداة  التشريعية يجب أن  يحتوى على أرقام  وليس حروف',
	    DECREE_TYPE_REQUIRED : 'يجب اختيار نوع الأداة  التشريعية',
	    DECREE_ISSUE_DATE_REQUIRED : 'يجب إدخال  تاريخ إصدار  الأداة  التشريعية (ميلادي  - هجري)',
	    DECREE_ATTACHMENT_REQUIRED : 'يجب إرفاق  مرفق الأداة  التشريعية',
	    DECREE_ATTACHMENT_ANOTHER_REQUIRED : 'يجب إرفاق  مرفق',
	    DECREE_ATTACHMENT_SIZE_MORE_THAN_5_MG : 'حجم المرفق يجب الا يزيد عن 5 ميجابايت',
	    FILE_SIZE : '5000000', // IN BYTES
	    DECREE_IS_ALREADY_EXISTS : 'المرجع موجود من قبل فى النظام',
	    DECREE_ISSUE_DATE_NOT_IN_FUTURE : 'لا يُسمح  أن  يكون تاريخ إصدار  الأداة  التشريعية الميلادي  متقدم على تاريخ اليوم',
	    MEMBER_TITLE : 'الأعضاء',
	    ISSUE_DATE_MELADY_LABLE :'تاريخ الإصدار  (ميلادي)',
	    ISSUE_DATE_HIJRY_LABLE : 'تاريخ الإصدار  (هجري)',
	    ARE_YOU_SURE : 'هل أنت  متاكد ؟',
	    CONFIRM_DECREE_DIALOG_BODY_MSG : 'هل أنت  متأكد  من حذف هذا المرجع ؟',
	    NO_BUTTON : 'لا',
	    YES_BUTTON :'نعم',
	    CONFIRM_DIALOG_HEADER : 'حذف المرجع',
	    CONFIRM_MEMBER_DIALOG_HEADER :'حذف العضو',
	    CONFIRM_MEMBER_DIALOG_BODY_MSG : 'هل انت متأكد من رغبتك في الحذف ؟',
	    DECREE_ISSUE_DATE_HIJRY_NOT_IN_FUTURE : 'لا يُسمح  أن  يكون تاريخ إصدار  الأداة  التشريعية (الهجري) متقدم على تاريخ اليوم',
	    MEMBER_END_DATE_AFTER_BOARD_END_DATE : 'لا يُسمح أن يكون تاريخ انتهاء العضوية متقدم على تاريخ انتهاء (اللجنة/المجلس)',
	    MEMBER_START_DATE_BEFORE_BOARD_START_DATE : 'لا يُسمح أن يكون تاريخ انضمام العضو قبل تاريخ تشكيل (اللجنة/المجلس)',
	    MEMBER_END_DATE_BEFORE_START_DATE : 'لا يُسمح أن يكون تاريخ تشكيل(اللجنة /المجلس )متقدم على تاريخ انتهائها',
	    BOARD_START_DATE_AND_END_DATE_REQUIRED : 'يجب ادخال تاريخ تشكيل(اللجنة /المجلس )وتاريخ انتهائها',
	    BOARD_DECREE_REQUIRED : 'يجب إرفاق مراجع في حالة إنشاء مجلس حكومي',
	    BOARD_START_DATE_NOT_IN_FUTURE : 'لا يُسمح أن يكون تاريخ تشكيل (اللجنة/المجلس) متقدم على تاريخ اليوم',
	    MEMBER_START_DATE_REQUIRED : 'يجب إدخال تاريخ انضمام العضو',
	    NOTIFICATION_TIMER_REPEATER : '60000',
	    EXE_FILE_TYPE :'exe',
	    EXE_FILE_TYPE_2:'application/x-msdownload',
	    ATTACHMENT_TYPE_EXE_NOT_ALLOWED :'لا يُسمح بإرفاق ملف من نوع (.exe)',
	    NOTES_LABEL : 'ملاحظات',
	    NOTES_PLACEHOLDER : 'الرجاء كتابة ملاحظاتك بما لا يزيد عن(250)حرف',
	    DELETE_ATTACHMENT_SUCCESSFULLY_MSG : 'تم إزالة الملف بنجاح',
	    SEARCH_BOARD_TITLE:'بحث لجنة/مجلس ',
	    GOVERNMENT_BOARD_TYPE_LABEL : 'نوع   اللجنة/المجلس',
	    SEARCH_BOARD_BUTTON:'بحث  اللجنة/المجلس',
	    TO_LABEL : 'إلى',
	    FROM_LABEL:'من',
	    SEARCH_BOARD_NO_RESULT_FOUND : 'لا يوجد نتائج للبحث ، الرجاء إدخال قيم أخرى لمحددات البحث',
	    SEARCH_START_DATE_TO_BEFORE_START_DATE_FROM : 'يجب ان يكون  تاريخ الإنشاء (الى) اكبر من تاريخ الإنشاء (من) ',
	    SEARCH_END_DATE_TO_BEFORE_END_DATE_FROM : 'يجب ان يكون  تاريخ الانتهاء  (الى) اكبر من تاريخ الانتهاء  (من)',
	    DECREE_YEAR_VALID_MSG : 'سنة الأداة التشريعية يجب أن تتكون من 4 أرقام',
	    BOARD_STATUS_LABEL : 'حالة   اللجنة / مجلس الإدارة',
	    BOARD_NOT_RELATED_TO_OTHER_BOARD : 'غير ( مرتبط / مرتبطة  ) بلجنة او مجلس إدارة',
	    BOARD_RELATED_TO_OTHER_BOARD : 'مرتبط / مرتبطة بأخرى',
	    BOARD_CREATION_TYPE_LABEL : 'اختر نوع (اللجنة/مجلس)',
	    PARENT_BOARD_LABLE : 'اختر (اللجنة/مجلس )المرتبط',
	    PARENT_BOARD_NAME_LABEL :'اسم (اللجنة/مجلس)المرتبط',
	    BOARD_NAME_ALREADY_EXIST : 'اسم (اللجنة/مجلس)موجود من قبل',
	    ALL_SEARCH_FIELDS_EMPTY : 'كل مدخلات البحث خالية يجب ادخال قيمة واحدة على الاقل',
	    SUCCESSFULLY_BOARD_CREATED : 'تم إضافة (اللجنة/مجلس) بنجاح',
	    BOARD_CREATION_FAILED : 'خطأ، لم يتم حفظ (اللجنة/مجلس)نجاح',
	    FILE_UPLOAD_FAILED : 'خطأ، لم يتم إرفاق المرفقات بنجاح',
	    DATABASE_ERROR : 'خطأ في النظام',
	    BOARD_SOURCE_ORGANIZATION_REQUIRED : 'يجب اختيار الجهة المعنية بالتعيين',
	    BOARD_DESTINATION_ORGANIZATION_REQUIRED : 'يجب اختيار الجهة المعنية مرة واحدة على الأقل',
	    BOARD_PARENT_IS_NOT_THE_SAME_BOARD_TYPE : 'يجب أن يكون نوع (اللجنة/المجلس)نفس نوع (اللجنة/المجلس)المرتبط به',
	    NOT_ALLOWED_NUMBERS : 'لا يُسمح بكتابة أرقام',
	    EXPORT_EXCEL : 'تنزيل اكسل',
	    EXPORT_PDF : 'تنزيل PDF',
	    SEARCH_BOARD_CLEAR_BUTTON:'إزالة محددات البحث',
	    BOARD_NAME_REQUIRED : 'يجب إدخال اسم (اللجنة/المجلس)',
	    BOARD_START_DATE_REQUIRED:'يجب إدخال تاريخ الإنشاء',
	    SEARCH_LABEL:'بحث',
	    BOARD_START_DATE_NOT_OLDER_DECREE_MELADY : 'لا يُسمح أن يكون تاريخ الأداة التشريعية متقدم على تاريخ إنشاء (اللجنة/المجلس)',
	    PERMIT_ONLY_ONE_DECREE:'يجب إضافة مرجع واحد فقط ',
	    ALL_FIELDS_EMPTY:'يجب إدخال قيمة واحدة على الأقل' , 
	    SEARCH_MEMBER_TITLE : 'بحث الأعضاء',
	    SEARCH_MEMBER_BUTTON : 'بحث الأعضاء',
	    MEMBER_STATUS_LABEL :'حالة الأعضاء',
	    UPDATE_BOARD_TITLE :'تعديل بيانات (اللجنة/المجلس)',
	    CANNOT_CHANGE_BOARD_TYPE : 'لا يُسمح تغيير نوع (اللجنة/المجلس)',
	    EDIT_BOARD_TITLE :'تعديل (لجنة/مجلس)',
	    RENEW_BUTTON_LABEL : 'تجديد',
	    MEMBER_EXPIRY_CANNOT_IN_PAST :'في حالة التجديد؛ لا يُسمح أن يكون تاريخ انتهاء العضوية مسبوقاً تاريخ اليوم',
	    SUCCESSFULLY_BOARD_UPDATED : 'تم تعديل بيانات (اللجنة/المجلس) بنجاح',
	    BOARD_UPDATED_FAILED : 'خطأ، لم يتم تعديل (اللجنة/مجلس)بنجاح',
	    UPDATE_BOARD_DECREE_REQUIRED :'في حالة إضافة أو تجديد عضو؛ يجب إرفاق مرجع',
	    DECREE_NOT_REQUIRED_INCASEOF_NO_NEW_MEMBER_OR_RENEW : 'لا يُسمح بإضافة مرجع بدون إضافة أو تجديد عضو ',
	    DECREE_NOT_FOUND_ERROR : 'خطأ في النظام، لم يتم إيجاد المراجع',
	    GENERAL_ERROR : 'خطأ في النظام',
	    CANCEL_BUTTON : 'إغلاق',
	    SAVE:'حفظ',
	    MEMBER_NOTIFICATION: 'إضافة تنبيه للعضو:',
	    MEMBER_NOTIFICATION_END_DATE_REQUIRED : 'لا يُسمح بإضافة تنبيهات للعضو بدون إضافة تاريخ انتهاء العضوية',
	    MEMBER_NOTIFICATION_ISSUE_DATE_EXCEPTION : 'خطأ، التاريخ المحتسب لأول تنبيه للعضو هو {NOTIFICATION_DATE} تاريخ سابق عن اليوم',
	    BOARD_NOTIFICATION_ISSUE_DATE_EXCEPTION : 'خطأ، التاريخ المحتسب لأول تنبيه (للجنة/للمجلس) هو {NOTIFICATION_DATE} تاريخ سابق عن اليوم',
	    VIEW_BOARD_LOG : 'عرض السجل (اللجنة/مجلس)',
	    VIEW_LOG_BUTTON : 'عرض السجل',
	    CREATED_BY_LABEL : 'بواسطة المستخدم',
	    CREATED_ON_LABEL : 'تاريخ الإضافة/التغيير',
	    VIEW_DECREES_LABLE : 'عرض المراجع' ,
	    ACTION_LABLE : 'نوع الإضافة/التعديل',
	    NO_DECREES_FOUND : 'لم يتم إيجاد مراجع',
	    VIEW_MEMBER_LOG : 'عرض السجل للعضو : '

	  };
})());