package bh.gov.cio.gbs.model;

public enum BoardSearchCriteria {
	
	
	
	GOVERNMENT_BOARD("GOVERNMENT_TYPE" , " GOVERNMENT_BOARD_TYPE_ID = :GOVERNMENT_TYPE  "),
	BOARD_NAME("BOARD_NAME"," BOARD_NAME_NORMALIZED LIKE :BOARD_NAME "),
	SOURCE_ORGANIZATION( "SOURCE_ORGANIZATION", " SOURCE_ORGANIZATION_ID = :SOURCE_ORGANIZATION "),
	DECREE_NUMBER("DECREE_NUMBER" , " DECREE_NUMBER = :DECREE_NUMBER "),
	DECREE_YEAR("DECREE_YEAR"," DECREE_YEAR = :DECREE_YEAR "),
	DECREE_TYPE("DECREE_TYPE" , " DECREE_TYPE_ID = :DECREE_TYPE "),
//	BETWEEN_START_DATE("BETWEEN_START_DATE"," BOARD_START_DATE BETWEEN ?  AND ? "),
	FROM_START_DATE("FROM_START_DATE"," DATE(BOARD_START_DATE) >= :FROM_START_DATE "),
	TO_START_DATE("TO_START_DATE"," DATE(BOARD_START_DATE) <= :TO_START_DATE  "),
//	BETWEEN_END_DATE("BETWEEN_END_DATE"," BOARD_EXPIRY_DATE BETWEEN ? AND ? "),
	FROM_END_DATE("FROM_END_DATE"," DATE(BOARD_EXPIRY_DATE) >= :FROM_END_DATE "),
	TO_END_DATE("TO_END_DATE"," DATE(BOARD_EXPIRY_DATE) <= :TO_END_DATE "),
	PRIMARY_DESTINATION_ORGANIZATION("PRIMARY_DESTINATION_ORGANIZATION" , " BOARD_ID IN ( SELECT DEO.BOARD_ID FROM GBS.BOARD_DESTINATION_ORGANIZATION DEO WHERE DESTINATION_ORGANIZATION_ID = :PRIMARY_DESTINATION_ORGANIZATION ) ") ,
	BOARD_STATUS("BOARD_STATUS" , " STATUS_ID= :BOARD_STATUS"),
	ATTACHMENT_TYPE("ATTACHMENT_TYPE"," ( ATTACHMENT_TYPE_ID = ( SELECT ATTACHMENT_TYPE_ID FROM GBS.ATTACHMENT_TYPE WHERE LOWER (FUNCTION_USED) = LOWER ('ADD_BOARD')) OR ATTACHMENT_TYPE_ID IS NULL) "); // UPDATED IN CASE OF NO DECREE
	
	private String query;
	private String param;
	
	BoardSearchCriteria(String param , String query){
		this.param = param;
		this.query = query;
	}

	public String getQuery() {
		return query;
	}

	public void setQuery(String query) {
		this.query = query;
	}

	public String getParam() {
		return param;
	}

	public void setParam(String param) {
		this.param = param;
	}
	
	
	
	
}
