/**
 * ******************************************************************
 * Copyrighted Material, Confidential, unauthorized review or 
 * reproduction is prohibited, ad so can and will result in 
 * legal action against violators 
 * ******************************************************************
 * ***  Copyright Holders *******************************************
 * ******************************************************************
 * Government of Kingdom Of Bahrain 						(KOB)	
 * Central Informatics Organization 						(CIO) 
 * Governerate Data Network 								(GDN) 
 * National Data Services Project							(NDS) 
 * The General Directorate of Information Technology 		(GDIT) 
 * Application Transformation Project 						(ATP)
 * Civil Registration Service 								(CRS)
 * ________________________________________________________________________________
 * Change Log 
 * ________________________________________________________________________________
 * VER		USER		Timestamp				Activity
 * ________________________________________________________________________________
 * 
 */

package bh.gov.cio.gbs.dataaccess;


/**
 * The Interface QueryStore.
 * 
 * @author Administrator
 */
public interface QueryStore {

	/** The empty query id. */
	String EMPTY_QUERY_ID = "EMPTY_QUERY_ID";

	/** The query map not initialized. */
	String QUERY_MAP_NOT_INITIALIZED = "QUERY_MAP_NOT_INITIALIZED";

	/** The query not found. */
	String QUERY_NOT_FOUND = "QUERY_NOT_FOUND";

	public interface Queries {

		String TEST_QUERY 												= "TEST_QUERY";
		String GET_ORGANIZATIONS_QUERY 									= "GET_ORGANIZATIONS_QUERY";
		String SEARCH_ORGANIZATION_QUERY 								= "SEARCH_ORGANIZATION_QUERY";
		String GET_SOURCE_ORGANIZATIONS_QUERY 							= "GET_SOURCE_ORGANIZATIONS_QUERY";
		String GET_DESTINATION_ORGANIZATIONS_QUERY 						= "GET_DESTINATION_ORGANIZATIONS_QUERY";
		String GET_MEMBERS_QUERY 										= "GET_MEMBERS_QUERY";
		String SEARCH_MEMBER_QUERY 										= "SEARCH_MEMBER_QUERY";
		String GET_BOARD_MEMBERS_QUERY 									= "GET_BOARD_MEMBERS_QUERY";
		String GET_BOARDS_DECREE_QUERY 									= "GET_BOARDS_DECREE_QUERY";
		String GET_ROLES_QUERY 											= "GET_ROLES_QUERY";
		String SEARCH_ROLE_QUERY 										= "SEARCH_ROLE_QUERY";
		String GET_DECREE_TYPES_QUERY 									= "GET_DECREE_TYPES_QUERY";
		String RECORD_LOGIN_HISTORY_QUERY 								= "RECORD_LOGIN_HISTORY_QUERY";
		String GET_ATTACHMENT_TYPES_QUERY 								= "GET_ATTACHMENT_TYPES_QUERY";
		String GET_RUNNABLE_NOTIFICATIONS_QUERY							= "GET_RUNNABLE_NOTIFICATIONS_QUERY";
		String RECORD_NOTIFICATION_HISTORY_QUERY 						= "RECORD_NOTIFICATION_HISTORY_QUERY";
		String GET_SUBSCRIBER_EMAIL_QUERY 								= "GET_SUBSCRIBER_EMAIL_QUERY";
		String GET_BOARD_TYPES_QUERY 									= "GET_BOARD_TYPES_QUERY";
		String GET_NOTIFICATION_PERIOD_QUERY 							= "GET_NOTIFICATION_PERIOD_QUERY";
		String UPDATE_NOTIFICATION_DATES_QUERY 							= "UPDATE_NOTIFICATION_DATES_QUERY";
		String GET_NOTIFICATION_REPEAT_QUERY 							= "GET_NOTIFICATION_REPEAT_QUERY";
		String ADD_BOARD_QUERY 											= "ADD_BOARD_QUERY";
		String IS_DECREE_EXISTS_QUERY 									= "IS_DECREE_EXISTS_QUERY";
		String ADD_DECREE_QUERY 										= "ADD_DECREE_QUERY";
		String ADD_BOARD_DECREE_QUERY									= "ADD_BOARD_DECREE_QUERY";
		String ADD_MEMBER_QUERY											= "ADD_MEMBER_QUERY";
		String ADD_MEMBER_DECREE_QUERY									= "ADD_MEMBER_DECREE_QUERY";
		String ADD_DESTINATION_ORGNIZATION_QUERY						= "ADD_DESTINATION_ORGNIZATION_QUERY";
		String ADD_NOTIFICATION_QUERY									= "ADD_NOTIFICATION_QUERY";
		String GET_BOARD_TYPE_QUERY 									= "GET_BOARD_TYPE_QUERY";
		String ADD_ATTACHMENT_QUERY 									= "ADD_ATTACHMENT_QUERY";
		String IS_BOARD_NAME_EXISTS_QUERY 								= "IS_BOARD_NAME_EXISTS_QUERY";
		String GET_BOARD_NOTIFICATIONS_QUERY 							= "GET_BOARD_NOTIFICATIONS_QUERY";
		String GET_GOVERNMENT_TYPES_QUERY 								= "GET_GOVERNMENT_TYPES_QUERY";
		String SEARCH_BOARD_QUERY 										= "SEARCH_BOARD_QUERY";
		String GET_BOARD_STATUS_LIST_QUERY 								= "GET_BOARD_STATUS_LIST_QUERY";
		String SEARCH_BOARD_TEXT_QUERY 									= "SEARCH_BOARD_TEXT_QUERY";
		String RECORD_BOARD_HISTORY_QUERY 								= "RECORD_BOARD_HISTORY_QUERY";
		String RECORD_MEMBER_HISTORY_QUERY 								= "RECORD_MEMBER_HISTORY_QUERY";
		String GET_BOARD_VALID_STATUS_QUERY 							= "GET_BOARD_VALID_STATUS_QUERY";
		String GET_MEMBER_VALID_STATUS_QUERY 							= "GET_MEMBER_VALID_STATUS_QUERY";
		String GET_BOARD_NEW_STATUS_QUERY 								= "GET_BOARD_NEW_STATUS_QUERY";
		String GET_USERNAME_BY_SESSION_ID_QUERY 						= "GET_USERNAME_BY_SESSION_ID_QUERY";
		String GET_ATTACHMENT_TYPE_DECREE_QUERY							= "GET_ATTACHMENT_TYPE_DECREE_QUERY";
		String ADD_SUBSCRIBER_QUERY 									= "ADD_SUBSCRIBER_QUERY";
		String GET_MEMBER_STATUS_LIST_QUERY 							= "GET_MEMBER_STATUS_LIST_QUERY";
		String SEARCH_MEMBER_FORM_QUERY 								= "SEARCH_MEMBER_FORM_QUERY";
		String GET_BOARD_NOTIFICATION_BY_ID_QUERY 						= "GET_BOARD_NOTIFICATION_BY_ID_QUERY";
		String GET_DECREES_BY_BOARD_ID_QUERY 							= "GET_DECREES_BY_BOARD_ID_QUERY";
		String GET_BOARD_QUERY 											= "GET_BOARD_QUERY";
		String GET_BOARD_DESTINATION_ORGANIZATIONS_QUERY 				= "GET_BOARD_DESTINATION_ORGANIZATIONS_QUERY";
		String GET_BOARD_MEMBER_QUERY 									= "GET_BOARD_MEMBER_QUERY";
		String UPDATE_BOARD_QUERY 										= "UPDATE_BOARD_QUERY";
		String UPDATE_NOTIFICATION_QUERY 								= "UPDATE_NOTIFICATION_QUERY";
		String UPDATE_SUBSCRIBER_QUERY									= "UPDATE_SUBSCRIBER_QUERY";
		String RENEW_MEMBER_QUERY 										= "RENEW_MEMBER_QUERY";
		String UPDATE_MEMBER_QUERY 										= "UPDATE_MEMBER_QUERY";
		String GET_ATTACHMENT_TYPE_FOR_MEMBER_QUERY 					= "GET_ATTACHMENT_TYPE_FOR_MEMBER_QUERY";
		String GET_NOTIFICATION_BY_BOARD_ID_QUERY 						= "GET_NOTIFICATION_BY_BOARD_ID_QUERY";
		String IS_SUBSCRIBER_EXISTS_QUERY 								= "IS_SUBSCRIBER_EXISTS_QUERY";
		String GET_MEMBER_QUERY 										= "GET_MEMBER_QUERY";
		String GET_MEMBER_INCOMPLETE_STATUS_QUERY 						= "GET_MEMBER_INCOMPLETE_STATUS_QUERY";
		String GET_BOARD_TYPE_NAME_QUERY 								= "GET_BOARD_TYPE_NAME_QUERY";
		String GET_MEMBERS_DECREES_QUERY 								= "GET_MEMBERS_DECREES_QUERY";
		String GET_BOARD_DECREES_QUERY 									= "GET_BOARD_DECREES_QUERY";
		String UPDATE_EXPIRED_BOARDS_STATUS_QUERY 						= "UPDATE_EXPIRED_BOARDS_STATUS_QUERY";
		String GET_EXPIRED_BOARDS_QUERY 								= "GET_EXPIRED_BOARDS_QUERY";
		String GET_MEMBER_STATUS_QUERY 									= "GET_MEMBER_STATUS_QUERY";
		String GET_BOARD_STATUS_QUERY 									= "GET_BOARD_STATUS_QUERY";
		String GET_BOARD_EXPIRED_STATUS_QUERY 							= "GET_BOARD_EXPIRED_STATUS_QUERY";
		String ADD_MEMBER_NOTIFICATION_QUERY 							= "ADD_MEMBER_NOTIFICATION_QUERY";
		String GET_BOARD_MEMBER_NOTIFICATIONS_QUERY 					= "GET_BOARD_MEMBER_NOTIFICATIONS_QUERY";
		String GET_BOARD_HISTORY_LOG_QUERY 								= "GET_BOARD_HISTORY_LOG_QUERY";
		String GET_MEMBER_HISTORY_LOG_QUERY 							= "GET_MEMBER_HISTORY_LOG_QUERY";
		String GET_MEMBER_NOTIFICATIONS_QUERY 							= "GET_MEMBER_NOTIFICATIONS_QUERY";
		String GET_EXPIRED_MEMBERS_QUERY 								= "GET_EXPIRED_MEMBERS_QUERY";
		String GET_MEMBER_EXPIRED_STATUS_QUERY 							= "GET_MEMBER_EXPIRED_STATUS_QUERY";
		String UPDATE_EXPIRED_MEMBERS_STATUS_QUERY 						= "UPDATE_EXPIRED_MEMBERS_STATUS_QUERY";
		String GET_MEMBER_DECREE_QUERY 									= "GET_MEMBER_DECREE_QUERY";
		String DELETE_SUBSCRIBER_QUERY 									= "DELETE_SUBSCRIBER_QUERY";
		String DELETE_NOTIFICATION_QUERY 								= "DELETE_NOTIFICATION_QUERY";
		String UPDATE_MEMBER_NOTIFICATION_QUERY 						= "UPDATE_MEMBER_NOTIFICATION_QUERY";
		String GET_NOTIFICATION_BY_MEMBER_ID_QUERY 						= "GET_NOTIFICATION_BY_MEMBER_ID_QUERY";
		String DELETE_MEMBER_SUBSCRIBER_QUERY 							= "DELETE_MEMBER_SUBSCRIBER_QUERY";
		String DELETE_MEMBER_NOTIFICATION_QUERY 						= "DELETE_MEMBER_NOTIFICATION_QUERY";
		String GET_ATTACHMENT_BY_BOARD_ID_QUERY 						= "GET_ATTACHMENT_BY_BOARD_ID_QUERY";
		String UPDATE_BOARD_STATUS_QUERY 								= "UPDATE_BOARD_STATUS_QUERY";
		String ADD_BOARD_WITHOUT_DECREE_QUERY 							= "ADD_BOARD_WITHOUT_DECREE_QUERY";
	}

}
