INSERT INTO GBS.DECREE_TYPE(DECREE_TYPE_ID, DECREE_TYPE_NAME, DECREE_TYPE_NAME_NORMALIZED, CREATED_BY, CREATED_ON, UPDATED_BY, UPDATED_ON, DISPLAY_SEQUENCE)
  VALUES(DEFAULT, 'قانون', 'قانون', NULL, NULL, NULL, NULL, 1),
  (DEFAULT, 'مرسوم بقانون', 'مرسوم بقانون', NULL, NULL, NULL, NULL, 2),
  (DEFAULT, 'مرسوم', 'مرسوم', NULL, NULL, NULL, NULL, 3),
  (DEFAULT, 'امر ملكي', 'أمر ملكي', NULL, NULL, NULL, NULL, 4),
  (DEFAULT, 'القرار', 'القرار', NULL, NULL, NULL, NULL, 5)
  Go